
export enum TransactionType {
    SWAP = "Swap",
    BUY_PROPERTY = "Buy Property",
    SELL_PROPERTY = "Sell Property",
    RENT_REDEEM = "Rent Redeem",
    RENT_CLAIM = "Rent Claim",
    VAULT_DEPOSIT = "Vault Deposit",
    VAULT_WITHDRAW = "Vault Withdraw",
    DEPOSIT = "Deposit",
    TOKEN_WITHDRAW = "Token Withdraw",
    NATIVE_WITHDRAW = "Native Withdraw",
    TRANSFER = "Transfer",
    RECOVERY = "Recovery",
    START_RECOVERY = "Start Recovery",
    VOTE_RECOVERY = "Vote Recovery",
    COMPLETE_RECOVERY = "Complete Recovery",
    ADD_PASSKEY = "Add PassKey",
    CREATE_ACCOUNT = "Create Account",
    BRIDGE_RWA = "Bridge RWA Tokens",
    CCTP_USDC = "Bridge USDC",
    CREATE_POSITION = "Create Position",
    ADD_COLLATERAL = 'Add Collateral',
    REMOVE_COLLATERAL = 'Remove Collateral',
    BORROW ='Borrow',
    REPAY = 'Repay',
    CLOSE_POSITION = 'Close position',
    POSITION_CLAIM = 'Claim position rent',
    CREATE_LEVERATE = 'Create Leverage'
  }